/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Center: typeof import('./src/components/page/center.vue')['default']
    CommentBlock: typeof import('./src/components/lib/comment/comment-block.vue')['default']
    CommentItem: typeof import('./src/components/lib/comment/comment-item.vue')['default']
    FundDetail: typeof import('./src/components/page/fund-detail.vue')['default']
    FundList: typeof import('./src/components/lib/fund/fund-list.vue')['default']
    Home: typeof import('./src/components/page/home.vue')['default']
    InputArea: typeof import('./src/components/lib/input-area.vue')['default']
    Login: typeof import('./src/components/page/user/login.vue')['default']
    Market: typeof import('./src/components/page/market.vue')['default']
    NaviBar: typeof import('./src/components/lib/navi-bar.vue')['default']
    Own: typeof import('./src/components/page/own.vue')['default']
    Post: typeof import('./src/components/page/post.vue')['default']
    PostDetail: typeof import('./src/components/page/post-detail.vue')['default']
    Regist: typeof import('./src/components/page/user/regist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonList: typeof import('./src/components/lib/skeleton-list.vue')['default']
    Star: typeof import('./src/components/page/star.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarRadio: typeof import('@varlet/ui')['_RadioComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSkeleton: typeof import('@varlet/ui')['_SkeletonComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarUploader: typeof import('@varlet/ui')['_UploaderComponent']
  }
}
