export const MENU_TYPE = {
    OPEN: 'open',
    LINK: 'link',
    FUNC: 'func'
};

export const EVENT = {
    THEME_CHANGE: 'THEME_CHANGE',
    OPEN_LIB_CHOOSE: 'OPEN_LIB_CHOOSE',
    CLOSE_LIB_CHOOSE: 'CLOSE_LIB_CHOOSE',
    OPEN_ENV_CHOOSE: 'OPEN_ENV_CHOOSE',
    CLOSE_ENV_CHOOSE: 'CLOSE_ENV_CHOOSE',
    OPEN_LANG_CHOOSE: 'OPEN_LANG_CHOOSE',
    CLOSE_LANG_CHOOSE: 'CLOSE_LANG_CHOOSE',
    LANG_CHANGE: 'LANG_CHANGE',
    RESIZE: 'RESIZE',
    CODE_CHANGE: 'CODE_CHANGE',
    USE_CODE: 'USE_CODE',
    HTML_PANEL_CHANGE: 'HTML_PANEL_CHANGE',
    HTML_CONTENT_CHANGE: 'HTML_CONTENT_CHANGE',

    // drag相关
    DRAG_PERCENT: 'DRAG_PERCENT',
    DRAG_STATUS: 'DRAG_STATUS',
};

export const TOOL_HEIGHT = 30;