/*
 * @Author: chenzhongsheng
 * @Date: 2022-11-05 00:06:41
 * @Description: Coding something
 * @LastEditors: Please set LastEditors
 * @LastEditTime: 2025-02-06 23:16:19
 */
export const MENU_TYPE = {
    OPEN: 'open',
    LINK: 'link',
    FUNC: 'func',
    SPLIT: 'split'
};

export const EVENT = {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_TOGGLE: 'THEME_TOGGLE',
    WORD_WRAP_CHANGE: 'WORD_WRAP_CHANGE',
    WORD_WRAP_TOGGLE: 'WORD_WRAP_TOGGLE',
    OPEN_LIB_CHOOSE: 'OPEN_LIB_CHOOSE',
    CLOSE_LIB_CHOOSE: 'CLOSE_LIB_CHOOSE',
    OPEN_ENV_CHOOSE: 'OPEN_ENV_CHOOSE',
    CLOSE_ENV_CHOOSE: 'CLOSE_ENV_CHOOSE',
    OPEN_LANG_CHOOSE: 'OPEN_LANG_CHOOSE',
    CLOSE_LANG_CHOOSE: 'CLOSE_LANG_CHOOSE',
    LANG_CHANGE: 'LANG_CHANGE',
    RESIZE: 'RESIZE',
    SET_CODE: 'SET_CODE',
    CODE_CHANGE: 'CODE_CHANGE',
    USE_CODE: 'USE_CODE',
    HTML_PANEL_CHANGE: 'HTML_PANEL_CHANGE',
    HTML_CONTENT_CHANGE: 'HTML_CONTENT_CHANGE',
    FONT_SIZE_CHANGE: 'FONT_SIZE_CHANGE',
    EDITOR_MOUNTED: 'EDITOR_MOUNTED',
    OPEN_CONFIRM: 'OPEN_CONFIRM',
    CLEAR_CODE: 'CLEAR_CODE',
    RESET_CODE: 'RESET_CODE',
    SAVE_CODE: 'SAVE_CODE',
    RUN_CODE: 'RUN_CODE',
    COPY_CODE: 'COPY_CODE',
    GENE_LINK: 'GENE_LINK',
    TOGGLE_LOG: 'TOGGLE_LOG',
    ADD_LIB: 'ADD_LIB',
    SET_ENV: 'SET_ENV',
    OPEN_DIFF: 'OPEN_DIFF',
    CURSOR_CHANGE: 'CURSOR_CHANGE',
    OPEN_FILE: 'OPEN_FILE',
    TOGGLE_FULLSCREEN: 'TOGGLE_FULLSCREEN',
    CONSOLE_VAL_CHANGE: 'CONSOLE_VAL_CHANGE',
    OPEN_CONFIG_CHOOSE: 'OPEN_CONFIG_CHOOSE',
    // drag相关
    DRAG_PERCENT: 'DRAG_PERCENT',
    DRAG_STATUS: 'DRAG_STATUS',

    // 配置有变化时
    JSBOX_CODE_CHANGE: 'JSBOX_CODE_CHANGE',

    CODE_MAP_INIT: 'CODE_MAP_INIT',
    STORE_CHANGE: 'STORE_CHANGE',

    CLEAR_LOG: 'CLEAR_LOG',

    RECOUNT_FILE_SIZE: 'RECOUNT_FILE_SIZE',

    SWITCH_CODE: 'SWITCH_CODE',

    IFRAME_SRC: 'IFRAME_SRC',

    UI_LANG_CHANGE: 'UI_LANG_CHANGE',
};

export const TOOL_HEIGHT = 30;