export const MENU_TYPE = {
    OPEN: 'open',
    LINK: 'link',
    FUNC: 'func'
};

export const EVENT = {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_TOGGLE: 'THEME_TOGGLE',
    OPEN_LIB_CHOOSE: 'OPEN_LIB_CHOOSE',
    CLOSE_LIB_CHOOSE: 'CLOSE_LIB_CHOOSE',
    OPEN_ENV_CHOOSE: 'OPEN_ENV_CHOOSE',
    CLOSE_ENV_CHOOSE: 'CLOSE_ENV_CHOOSE',
    OPEN_LANG_CHOOSE: 'OPEN_LANG_CHOOSE',
    CLOSE_LANG_CHOOSE: 'CLOSE_LANG_CHOOSE',
    LANG_CHANGE: 'LANG_CHANGE',
    RESIZE: 'RESIZE',
    SET_CODE: 'SET_CODE',
    CODE_CHANGE: 'CODE_CHANGE',
    USE_CODE: 'USE_CODE',
    HTML_PANEL_CHANGE: 'HTML_PANEL_CHANGE',
    HTML_CONTENT_CHANGE: 'HTML_CONTENT_CHANGE',
    FONT_SIZE_CHANGE: 'FONT_SIZE_CHANGE',
    EDITOR_MOUNTED: 'EDITOR_MOUNTED',
    OPEN_CONFIRM: 'OPEN_CONFIRM',
    CLEAR_CODE: 'CLEAR_CODE',
    RESET_CODE: 'RESET_CODE',
    SAVE_CODE: 'SAVE_CODE',
    RUN_CODE: 'RUN_CODE',
    COPY_CODE: 'COPY_CODE',
    GENE_LINK: 'GENE_LINK',
    TOGGLE_LOG: 'TOGGLE_LOG',
    ADD_LIB: 'ADD_LIB',
    SET_ENV: 'SET_ENV',
    OPEN_DIFF: 'OPEN_DIFF',
    CURSOR_CHANGE: 'CURSOR_CHANGE',
    OPEN_FILE: 'OPEN_FILE',
    // drag相关
    DRAG_PERCENT: 'DRAG_PERCENT',
    DRAG_STATUS: 'DRAG_STATUS',
};

export const TOOL_HEIGHT = 30;