module.exports = [
    'jQuery',
    'vue',
    'react',
    'angular',
    'vuex',
    'redux',
    'loadsh',
    'virtual-dom',
    'node-html-parser',
    'jest',
    'mocha',
    'moment',
    'dayjs',
    'underscore',
    'axios',
    'element-ui',
    'js-xlsx',
    'qrcode',
    'backbone'
];

[ 'https://cdn.jsdelivr.net/npm/underscore@1.9.2/underscore.min.js',
    'js-xlsx@0.8.22',
    'https://cdn.jsdelivr.net/npm/virtual-dom@2.1.1/dist/virtual-dom.js',
    'https://cdn.jsdelivr.net/npm/jest@25.1.0/build/jest.min.js',
    'https://cdn.jsdelivr.net/npm/redux@4.0.5/lib/redux.min.js',
    'https://cdn.jsdelivr.net/npm/jQuery@1.7.4/lib/node-jquery.js',
    'https://cdn.jsdelivr.net/npm/axios@0.19.2/index.min.js',
    'https://cdn.jsdelivr.net/npm/mocha@7.1.1/lib/mocha.js',
    'https://cdn.jsdelivr.net/npm/angular@1.7.9/index.min.js',
    'https://cdn.jsdelivr.net/npm/vuex@3.1.3/dist/vuex.min.js',
    'https://cdn.jsdelivr.net/npm/backbone@1.4.0/backbone.min.js',
    'https://cdn.jsdelivr.net/npm/react@16.13.0/index.min.js',
    'https://cdn.jsdelivr.net/npm/qrcode@1.4.4/lib/index.min.js',
    'https://cdn.jsdelivr.net/npm/node-html-parser@1.2.13/dist/index.min.js',
    'https://cdn.jsdelivr.net/npm/moment@2.24.0/moment.min.js',
    'https://cdn.jsdelivr.net/npm/dayjs@1.8.23/dayjs.min.js',
    'https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js',
    'https://cdn.jsdelivr.net/npm/loadsh@0.0.4/lodash.min.js',
    'https://cdn.jsdelivr.net/npm/element-ui@2.13.0/lib/element-ui.common.min.js' ];
